apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: devpulse
spec:
  containers:
  - name: test-container
    image: busybox
    command: ["/bin/sh", "-c", "while true; do echo '{\"timestamp\": \"$(date -u +%Y-%m-%dT%H:%M:%SZ)\", \"service\": \"test-pod\", \"logLevel\": \"INFO\", \"message\": \"Pod running\", \"metadata\": {}}'; sleep 5; done"]